listeners:
  default:
    type: tcp
    bind: 0.0.0.0:1883
    max-connections: 50000
  websocket:
    type: ws
    bind: 0.0.0.0:1884
    max-connections: 50000
sys_interval: 10
auth:
  plugins:
  - auth_file
  - auth_anonymous
  allow-anonymous: true
  password-file: list